export const miPerfilLang = {
  es: {
    'editar': "editar",
    'quitar':'quitar',
    'nombreCompleto':'nombre completo',
    'correoElectronico':'correo electronico',
    'verificado': 'verificado',
    'verificar':'verificar',
    'nombreDelUsuario':'Nombre del usuario',
    'modificar':'Modificar',
    'direccion':'Direccion',
    'contraseña':'Contraseña',
    'cambiarContraseña':'Cambiar contraseña',
    'noEstasLogueado':'No estas logueado',
  },

  en: {
    'editar': "edit",
    'quitar':'take off',
    'nombreCompleto':'full name',
    'correoElectronico':'email',
    'verificado': 'verified',
    'verificar':'verify',
    'nombreDelUsuario':'Username',
    'modificar':'Change',
    'direccion':'Address',
    'contraseña':'Password',
    'cambiarContraseña':'Change password',
    'noEstasLogueado':'You are not logged in',
  },
};
